Writeopia/Writeopia

- storyteller/src/main/java/br/com/leandroferreira/storyteller/drawer/content/CheckItemDrawer.kt
- storyteller/src/main/java/br/com/leandroferreira/storyteller/manager/FindStory.kt
- storyteller/src/main/java/br/com/leandroferreira/storyteller/manager/StoryTellerManager.kt
- storyteller/src/main/java/br/com/leandroferreira/storyteller/model/story/GroupStep.kt
- storyteller/src/main/java/br/com/leandroferreira/storyteller/model/story/StoryStep.kt
- storyteller/src/test/java/br/com/leandroferreira/storyteller/manager/StoryTellerManagerTest.kt
- storyteller/src/test/java/br/com/leandroferreira/storyteller/utils/MapStoryData.kt
Fixing line break and remove content by erasing text
> Line break fix

- storyteller/src/main/java/br/com/leandroferreira/storyteller/backstack/BackStackManager.kt
- storyteller/src/main/java/br/com/leandroferreira/storyteller/drawer/content/CheckItemDrawer.kt
- storyteller/src/main/java/br/com/leandroferreira/storyteller/model/backtrack/AddText.kt
- storyteller/src/main/java/br/com/leandroferreira/storyteller/model/change/TextEditInfo.kt
- storyteller/src/test/java/br/com/leandroferreira/storyteller/backstack/BackStackManagerTest.kt
Adding just the logic as BackStackManager, but not implementing the integration with it.
> Backstack - Adding logic

- .idea/kotlinc.xml
- app_sample/build.gradle.kts
- app_sample/src/main/AndroidManifest.xml
- app_sample/src/main/java/br/com/leandroferreira/app_sample/navigation/NavigationActivity.kt
- app_sample/src/main/java/br/com/leandroferreira/app_sample/screens/addstory/StoriesViewModel.kt
- app_sample/src/main/java/br/com/leandroferreira/app_sample/screens/note/NoteDetailsScreen.kt
- app_sample/src/main/java/br/com/leandroferreira/app_sample/screens/note/NoteDetailsViewModel.kt
- app_sample/src/main/java/br/com/leandroferreira/app_sample/screens/note/input/InputScreen.kt
- app_sample/src/main/res/values/strings.xml
- build.gradle
- build.gradle.kts
- storyteller/build.gradle.kts
- storyteller/src/main/java/br/com/leandroferreira/storyteller/StoryTellerTimeline.kt
- storyteller/src/main/java/br/com/leandroferreira/storyteller/backstack/BackStackManager.kt
- storyteller/src/main/java/br/com/leandroferreira/storyteller/backstack/BackstackHandler.kt
- storyteller/src/main/java/br/com/leandroferreira/storyteller/backstack/BackstackInform.kt
- storyteller/src/main/java/br/com/leandroferreira/storyteller/drawer/content/CheckItemDrawer.kt
- storyteller/src/main/java/br/com/leandroferreira/storyteller/drawer/content/SpaceDrawer.kt
- storyteller/src/main/java/br/com/leandroferreira/storyteller/manager/StoryTellerManager.kt
- storyteller/src/main/java/br/com/leandroferreira/storyteller/model/backtrack/AddStoryUnit.kt
- storyteller/src/test/java/br/com/leandroferreira/storyteller/backstack/BackStackManagerTest.kt
- storyteller/src/test/java/br/com/leandroferreira/storyteller/manager/StoryTellerManagerTest.kt
- storyteller_persistence/build.gradle.kts
- storyteller_persistence/src/main/java/br/com/leandroferreira/storyteller/persistence/repository/DocumentRepository.kt
Backstack for text edition is still now working, but merging the PR to avoid it to become too big.
> Back stack UI

- app_sample/src/main/java/br/com/leandroferreira/app_sample/screens/note/NoteDetailsScreen.kt
- app_sample/src/main/java/br/com/leandroferreira/app_sample/screens/note/NoteDetailsViewModel.kt
- storyteller/src/main/java/br/com/leandroferreira/storyteller/manager/StoryStateSaver.kt
- storyteller/src/main/java/br/com/leandroferreira/storyteller/manager/StoryTellerManager.kt
- storyteller_persistence/src/main/java/br/com/leandroferreira/storyteller/persistence/repository/DocumentRepository.kt
Now the sample apps saves all the time instead of providing a button written "Save"
> Saving as user edits instead of pressing a button

- storyteller/src/main/java/com/github/leandroborgesferreira/storyteller/draganddrop/target/DragTarget.kt
- storyteller/src/main/java/com/github/leandroborgesferreira/storyteller/draganddrop/target/DragTargetWithDragItem.kt
- storyteller/src/main/java/com/github/leandroborgesferreira/storyteller/drawer/DefaultDrawers.kt
- storyteller/src/main/java/com/github/leandroborgesferreira/storyteller/drawer/content/CheckItemDrawer.kt
- storyteller/src/main/java/com/github/leandroborgesferreira/storyteller/drawer/content/LargeEmptySpace.kt
Making checkitems easier to move by dragging.
> Drag improvement

- storyteller/src/main/java/com/github/leandroborgesferreira/storyteller/manager/MovementHandler.kt
- storyteller/src/main/java/com/github/leandroborgesferreira/storyteller/manager/StoryTellerManager.kt
Created new class that handles moves and merges of steps
> extracting movement logic

- storyteller/src/main/java/com/github/leandroborgesferreira/storyteller/drawer/content/CheckItemDrawer.kt
- storyteller/src/main/res/values/strings.xml
Adding a button to delete check items more easily.
> Check item delete

- storyteller/src/main/java/com/github/leandroborgesferreira/storyteller/drawer/DefaultDrawers.kt
- storyteller/src/main/java/com/github/leandroborgesferreira/storyteller/drawer/content/TitleDrawer.kt
- storyteller/src/main/java/com/github/leandroborgesferreira/storyteller/manager/StoryTellerManager.kt
- storyteller/src/main/java/com/github/leandroborgesferreira/storyteller/model/story/StoryType.kt
- storyteller/src/main/res/values/strings.xml
> Title drawer

- storyteller/src/main/java/com/github/leandroborgesferreira/storyteller/drawer/DefaultDrawers.kt
- storyteller/src/main/java/com/github/leandroborgesferreira/storyteller/drawer/content/MessageDrawer.kt
- storyteller/src/main/java/com/github/leandroborgesferreira/storyteller/manager/ContentHandler.kt
- storyteller/src/main/java/com/github/leandroborgesferreira/storyteller/manager/StoryTellerManager.kt
- storyteller/src/main/java/com/github/leandroborgesferreira/storyteller/model/command/Command.kt
- storyteller/src/main/java/com/github/leandroborgesferreira/storyteller/model/command/CommandInfo.kt
- storyteller/src/main/java/com/github/leandroborgesferreira/storyteller/model/command/CommandTrigger.kt
- storyteller/src/main/java/com/github/leandroborgesferreira/storyteller/model/story/StoryTypes.kt
- storyteller/src/test/java/com/github/leandroborgesferreira/storyteller/manager/ContentHandlerTest.kt
Fixing the check item command, now it keeps the current text when changing the type. 
Adding h1, h2, h3, e h4 as command.
> Adding h1, h2, h3 and h4. Also fixing check item command

- application/desktopApp/src/jvmMain/kotlin/io/writeopia/notes/desktop/Main.kt
- application/web/src/jsMain/kotlin/Data.kt
- application/web/src/jsMain/kotlin/DefaultDrawersJs.kt
- application/web/src/jsMain/kotlin/JsMessageDrawer.kt
- application/web/src/jsMain/kotlin/Main.kt
- writeopia/src/commonMain/kotlin/io/writeopia/sdk/WriteopiaEditor.kt
- writeopia/src/commonMain/kotlin/io/writeopia/sdk/WriteopiaEditorBox.kt
- writeopia/src/commonMain/kotlin/io/writeopia/sdk/draganddrop/target/DraggableScreen.kt
- writeopia/src/commonMain/kotlin/io/writeopia/sdk/utils/ui/defaultTextStyle.kt
- writeopia/src/jvmMain/kotlin/io/writeopia/sdk/drawer/factory/DefaultDrawersDesktop.kt
Improving the appearance of web and desktop editors. 
The web app still has some buggy behaviors when breaking lines.
> Web and Desktop Apps Polish

- application/androidApp/src/androidMain/kotlin/io/writeopia/application/WriteopiaApplication.kt
- application/auth_core/src/main/java/io/writeopia/auth/core/di/AuthCoreInjection.kt
- application/auth_core/src/main/java/io/writeopia/auth/core/manager/AmplifyAuthManager.kt
- application/auth_core/src/main/java/io/writeopia/auth/core/manager/AuthManager.kt
- application/auth_core/src/main/java/io/writeopia/auth/core/manager/MockAuthManager.kt
- application/features/account/src/main/java/io/writeopia/account/navigation/AccountNavigation.kt
- application/features/account/src/main/java/io/writeopia/account/viewmodel/AccountMenuViewModel.kt
- application/features/auth/src/main/java/io/writeopia/auth/di/AuthInjection.kt
- application/features/auth/src/main/java/io/writeopia/auth/login/LoginViewModel.kt
- application/features/auth/src/main/java/io/writeopia/auth/menu/AuthMenuViewModel.kt
- application/features/auth/src/main/java/io/writeopia/auth/register/RegisterViewModel.kt
- application/features/editor/src/main/java/io/writeopia/editor/di/EditorInjector.kt
- application/features/note_menu/src/main/java/io/writeopia/note_menu/di/NotesMenunjection.kt
- application/features/note_menu/src/main/java/io/writeopia/note_menu/di/ViewModelFactories.kt
- application/features/note_menu/src/main/java/io/writeopia/note_menu/ui/screen/menu/ChooseNoteScreen.kt
- application/features/note_menu/src/main/java/io/writeopia/note_menu/viewmodel/ChooseNoteViewModel.kt
Injecting mock version of auth when build type if DEBUG
> Mocking auth

- application/desktopApp/src/jvmMain/kotlin/io/writeopia/notes/desktop/Main.kt
- application/web/src/jsMain/kotlin/Main.kt
By using scroll, the sample doesn't get stuck in the last line
> Adding scroll to desktop sample

- application/common_flows/wide_screen_common/src/commonMain/kotlin/io/writeopia/notes/desktop/components/App.kt
- writeopia/src/commonMain/kotlin/io/writeopia/sdk/manager/ContentHandler.kt
- writeopia/src/commonTest/kotlin/io/writeopia/manager/ContentHandlerTest.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/edition/TextCommandHandler.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/manager/WriteopiaStateManager.kt
This PR fixes the written commands
> Text command fix

- application/androidApp/src/androidMain/kotlin/io/writeopia/navigation/NavigationActivity.kt
- application/common_flows/wide_screen_common/src/commonMain/kotlin/io/writeopia/notes/desktop/components/App.kt
- application/core/auth_core/src/commonMain/kotlin/io/writeopia/auth/core/utils/Constants.kt
- application/core/persistence_sqldelight/src/commonMain/kotlin/io/writeopia/sqldelight/theme/UiConfigurationSqlDelightDao.kt
- application/core/persistence_sqldelight/src/commonMain/sqldelight/io/writeopia/app/sql/UiConfigurationEntity.sq
- application/core/theme/src/androidMain/kotlin/io/writeopia/repository/UiConfigurationPreferenceDao.kt
- application/core/theme/src/androidMain/kotlin/io/writeopia/repository/UiConfigurationRepositoryImpl.kt
- application/core/theme/src/androidMain/kotlin/io/writeopia/repository/extensions/UiConfigurationRoomExtensions.kt
- application/core/theme/src/commonMain/kotlin/io/writeopia/extensions/UiConfigurationExtensions.kt
- application/core/theme/src/commonMain/kotlin/io/writeopia/model/UiConfiguration.kt
- application/core/theme/src/commonMain/kotlin/io/writeopia/repository/UiConfigurationMemoryRepository.kt
- application/core/theme/src/commonMain/kotlin/io/writeopia/repository/UiConfigurationSqlDelightRepository.kt
- application/core/theme/src/commonMain/kotlin/io/writeopia/viewmodel/UiConfigurationKmpViewModel.kt
- application/core/theme/src/commonTest/kotlin/io/writeopia/repository/UiConfigurationRepositoryCommonTest.kt
- application/desktopApp/src/jvmMain/kotlin/io/writeopia/desktop/MainDesktop.kt
- application/features/global_shell/build.gradle.kts
- application/features/global_shell/config/ktlint/baseline.xml
- application/features/global_shell/src/commonMain/kotlin/io/writeopia/global/shell/SideGlobalMenu.kt
- application/features/global_shell/src/commonMain/kotlin/io/writeopia/global/shell/viewmodel/GlobalShellKmpViewModel.kt
- application/features/global_shell/src/commonMain/kotlin/io/writeopia/global/shell/viewmodel/GlobalShellViewModel.kt
- application/features/note_menu/config/ktlint/baseline.xml
- application/web/src/jsMain/kotlin/io/writeopia/web/MainWeb.kt
In this PR: 
Now it is possible to move the side menu in the desktop and web apps. The user can drag it to change the width. The width is persisted
> Side menu drag

- plugins/writeopia_persistence_room/src/main/java/io/writeopia/sdk/persistence/entity/story/StoryStepEntity.kt
- plugins/writeopia_persistence_room/src/main/java/io/writeopia/sdk/persistence/parse/StoryUnitParse.kt
- plugins/writeopia_persistence_sqldelight/src/commonMain/kotlin/io/writeopia/sdk/persistence/sqldelight/dao/DocumentSqlDao.kt
- plugins/writeopia_serialization/src/commonMain/kotlin/io/writeopia/sdk/serialization/data/DecorationApi.kt
- plugins/writeopia_serialization/src/commonMain/kotlin/io/writeopia/sdk/serialization/data/StoryStepApi.kt
- plugins/writeopia_serialization/src/commonMain/kotlin/io/writeopia/sdk/serialization/extensions/StoryStepExtensions.kt
- writeopia/src/commonMain/kotlin/io/writeopia/sdk/manager/ContentHandler.kt
- writeopia_models/src/commonMain/kotlin/io/writeopia/sdk/models/story/Decoration.kt
- writeopia_models/src/commonMain/kotlin/io/writeopia/sdk/models/story/StoryStep.kt
- writeopia_models/src/commonMain/kotlin/io/writeopia/sdk/models/story/Tags.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/HeaderDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/edition/TextCommandHandler.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/utils/defaultTextStyle.kt
This PR fixes the persistence of HX titles
> Fixing HX persistence

- application/desktopApp/src/jvmMain/kotlin/io/writeopia/desktop/MainDesktop.kt
- plugins/writeopia_persistence_sqldelight/build.gradle.kts
- plugins/writeopia_persistence_sqldelight/src/commonMain/kotlin/io/writeopia/sdk/persistence/sqldelight/dao/DocumentSqlDao.kt
- plugins/writeopia_persistence_sqldelight/src/commonMain/sqldelight/io/writeopia/sdk/sql/StoryStepEntity.sq
- plugins/writeopia_persistence_sqldelight/src/jvmTest/kotlin/io/writeopia/sdk/persistence/sqldelight/dao/sql/SqlDelightDocumentRepositoryTest.kt
- writeopia/src/commonMain/kotlin/io/writeopia/sdk/manager/WriteopiaManager.kt
Fixing the deletion of content when edition a text
> Fixing deletion of content

- application/desktopApp/src/jvmMain/kotlin/io/writeopia/desktop/MainDesktop.kt
- writeopia/src/commonMain/kotlin/io/writeopia/sdk/manager/WriteopiaManager.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/HeaderDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/TextDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/factory/CommonDrawers.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/factory/KeyEventListenerFactory.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/keyboard/KeyboardEvent.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/manager/WriteopiaStateManager.kt
This PR improves some keyboard commands and making navigating thought text better
> Keyboad commands

- writeopia/src/commonMain/kotlin/io/writeopia/sdk/manager/WriteopiaManager.kt
- writeopia/src/commonMain/kotlin/io/writeopia/sdk/model/story/Selection.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/WriteopiaEditorBox.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/TextDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/manager/WriteopiaStateManager.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/model/DrawInfo.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/model/DrawStory.kt
In this PR: 
- Fixing selection of text
> Fixing selection of text

- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/manager/WriteopiaStateManager.kt
Moving to the last position of the line when clicking at the end of document.
> End click fix

- .idea/artifacts/writeopia_persistence_sqldelight_js.xml
- .idea/artifacts/writeopia_persistence_sqldelight_jvm.xml
- writeopia/src/commonMain/kotlin/io/writeopia/sdk/manager/FocusHandler.kt
In this MR: Now the line jump works with list items too.
> Fixing line jump

- writeopia/src/commonMain/kotlin/io/writeopia/sdk/manager/ContentHandler.kt
- writeopia_models/src/commonMain/kotlin/io/writeopia/sdk/models/story/Tags.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/DesktopTextItemDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/utils/defaultTextStyle.kt
Fixing the persistence of tags for text markers like H1
> fix(database): Tags persistence fix

- .idea/artifacts/writeopia_persistence_sqldelight_js.xml
- .idea/artifacts/writeopia_persistence_sqldelight_jvm.xml
- application/androidApp/build.gradle.kts
- application/androidApp/src/androidMain/kotlin/io/writeopia/navigation/NavigationActivity.kt
- application/common_flows/wide_screen_common/.run/desktop.run.xml
- application/common_flows/wide_screen_common/src/commonMain/kotlin/io/writeopia/notes/desktop/components/App.kt
- application/features/editor/src/androidMain/kotlin/io/writeopia/editor/features/editor/ui/screen/NoteEditorScreen.kt
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/ui/TextEditor.kt
- writeopia_ui/src/androidMain/kotlin/io/writeopia/ui/drawer/factory/DefaultDrawersAndroid.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/WriteopiaEditor.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/CheckItemDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/DesktopTextItemDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/HeaderDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/SwipeMessageDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/TextDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/UnOrderedListItemDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/factory/CommonDrawers.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/preview/CheckItemPreviewDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/preview/TextPreviewDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/preview/UnOrderedListItemPreviewDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/manager/WriteopiaStateManager.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/model/DrawConfig.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/model/DrawStory.kt
- writeopia_ui/src/jsMain/kotlin/io/writeopia/ui/drawer/factory/DefaultDrawersJs.kt
- writeopia_ui/src/jvmMain/kotlin/io/writeopia/ui/drawer/factory/DefaultDrawersDesktop.kt
In this PR:
- Adding signing configuration
- Fixing paddings. Making it look good in mobile and desktop. Creating a configuration for paddings. 
- Fixing edition of text in mobile. This may need further investigation in a later moment.
> Padding fixes

- application/features/editor/src/androidMain/kotlin/io/writeopia/editor/features/editor/ui/screen/NoteEditorScreen.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/HeaderDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/factory/CommonDrawers.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/model/DrawConfig.kt
in this PR:
- Reducing the size of titles. 
- Making customization of titles simpler. 
- Adding overflow for title in toolbar
> fix(UI): Fixing title style

- application/core/persistence_sqldelight/src/commonMain/kotlin/io/writeopia/sqldelight/di/SqlDelightDaoInjector.kt
- backend/editor/api_editor/src/main/java/io/writeopia/api/editor/WriteopiaEditorApi.kt
- libraries/dbtest/src/commonMain/kotlin/io/writeopia/libraries/dbtests/DocumentRepositoryTests.kt
- plugins/writeopia_persistence_sqldelight/src/commonMain/kotlin/io/writeopia/sdk/persistence/sqldelight/dao/DocumentSqlDao.kt
- plugins/writeopia_persistence_sqldelight/src/jvmTest/kotlin/io/writeopia/sdk/persistence/sqldelight/dao/sql/SqlDelightDocumentRepositoryTest.kt
- writeopia_models/build.gradle.kts
- writeopia_models/src/commonMain/kotlin/io/writeopia/sdk/models/story/Tag.kt
Removing JSON to serialize tags
> refactor: Fix serialization of tags

- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/ui/desktop/edit/menu/SideEditorOptions.kt
- writeopia/src/commonMain/kotlin/io/writeopia/sdk/manager/ContentHandler.kt
- writeopia/src/commonMain/kotlin/io/writeopia/sdk/manager/WriteopiaManager.kt
- writeopia_models/src/commonMain/kotlin/io/writeopia/sdk/models/command/CommandInfo.kt
- writeopia_models/src/commonMain/kotlin/io/writeopia/sdk/models/story/Tag.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/SpaceDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/decorations/DefaultTagDecoration.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/factory/KeyEventListenerFactory.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/manager/WriteopiaStateManager.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/model/DrawConfig.kt
Fixing paddings and border for highlight box. Now a highlight box alone is not square anymore.
> feat(UI): Highlight block position

- application/core/theme/src/androidMain/kotlin/io/writeopia/repository/UiConfigurationPreferenceDao.kt
- application/core/theme/src/androidMain/kotlin/io/writeopia/repository/entity/UiConfigurationRoomEntity.kt
- application/core/theme/src/androidMain/kotlin/io/writeopia/repository/extensions/UiConfigurationRoomExtensions.kt
- application/features/editor/src/androidMain/kotlin/io/writeopia/editor/features/editor/ui/screen/NoteEditorScreen.kt
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/configuration/ui/NoteGlobalActionsMenu.kt
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/ui/desktop/DesktopNoteEditorScreen.kt
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/ui/desktop/edit/menu/SideEditorOptions.kt
- application/features/editor/src/nativeMain/kotlin/io/writeopia/editor/features/editor/ui/screen/NoteEditorScreen.kt
Adding font change for mobile. Currently is is only available on desktop app.
> feat: Adding font change for mobile

- application/features/note_menu/src/commonMain/kotlin/io/writeopia/notemenu/ui/screen/documents/NoteItems.kt
Fixing shadows for note items. Grid view and list view are not showing shadows at the moment.
> fix(UI): Fixing shadow for note items

- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/ui/TextEditor.kt
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/viewmodel/NoteEditorKmpViewModel.kt
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/viewmodel/NoteEditorViewModel.kt
- plugins/writeopia_persistence_core/src/commonMain/kotlin/io/writeopia/sdk/persistence/core/repository/DocumentRepository.kt
- plugins/writeopia_persistence_sqldelight/src/commonMain/kotlin/io/writeopia/sdk/persistence/sqldelight/dao/DocumentSqlDao.kt
- plugins/writeopia_persistence_sqldelight/src/commonMain/kotlin/io/writeopia/sdk/persistence/sqldelight/dao/sql/SqlDelightDocumentRepository.kt
- plugins/writeopia_persistence_sqldelight/src/commonMain/sqldelight/io/writeopia/sdk/sql/DocumentEntity.sq
- writeopia/src/commonMain/kotlin/io/writeopia/sdk/model/document/DocumentInfo.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/WriteopiaEditor.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/HeaderDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/manager/WriteopiaStateManager.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/model/DrawStory.kt
Adding icons in the title of the document
> feat: Header drawer icons

- application/composeApp/build.gradle.kts
- writeopia_ui/src/androidMain/kotlin/io/writeopia/ui/drawer/factory/DefaultDrawersAndroid.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/HeaderDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/manager/WriteopiaStateManager.kt
- writeopia_ui/src/jsMain/kotlin/io/writeopia/ui/drawer/factory/DefaultDrawersJs.kt
- writeopia_ui/src/jvmMain/kotlin/io/writeopia/ui/drawer/factory/DefaultDrawersDesktop.kt
Adding section selection when long click in header arrow
> adding section selection

- writeopia/src/commonMain/kotlin/io/writeopia/sdk/manager/MovementHandler.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/manager/WriteopiaStateManager.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/modifiers/StepsModifier.kt
- writeopia_ui/src/commonTest/kotlin/io/writeopia/ui/manager/WriteopiaStateManagerTest.kt
> Fixing move

- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/configuration/ui/HeaderEditionOptions.kt
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/viewmodel/NoteEditorKmpViewModel.kt
- application/features/global_shell/src/commonMain/kotlin/io/writeopia/global/shell/viewmodel/GlobalShellKmpViewModel.kt
- writeopia_ui/src/androidMain/kotlin/io/writeopia/ui/draganddrop/target/DragRowTarget.android.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/draganddrop/target/DragRowTarget.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/CheckItemDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/DesktopTextItemDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/SwipeMessageDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/UnOrderedListItemDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/factory/CommonDrawers.kt
- writeopia_ui/src/jsMain/kotlin/io/writeopia/ui/draganddrop/target/DragRowTarget.js.kt
- writeopia_ui/src/jvmMain/kotlin/io/writeopia/ui/draganddrop/target/DragRowTarget.jvm.kt
- writeopia_ui/src/nativeMain/kotlin/io/writeopia/ui/draganddrop/target/DragRowTarget.native.kt
When click in the drag icon for stories, now it triggers a selection
> Adding click for selection

- kotlin-js-store/yarn.lock
- plugins/writeopia_serialization/src/commonMain/kotlin/io/writeopia/sdk/serialization/data/StoryStepApi.kt
- plugins/writeopia_serialization/src/commonMain/kotlin/io/writeopia/sdk/serialization/data/TagInfoApi.kt
- plugins/writeopia_serialization/src/commonMain/kotlin/io/writeopia/sdk/serialization/extensions/StoryStepExtensions.kt
- plugins/writeopia_serialization/src/commonMain/kotlin/io/writeopia/sdk/serialization/extensions/TagInfoExtension.kt
- writeopia_models/src/commonMain/kotlin/io/writeopia/sdk/models/story/StoryStep.kt
- writeopia_ui/src/androidMain/kotlin/io/writeopia/ui/draganddrop/target/DragCardTarget.android.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/draganddrop/target/DragCardTarget.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/ImageDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/factory/CommonDrawers.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/manager/WriteopiaStateManager.kt
- writeopia_ui/src/jsMain/kotlin/io/writeopia/ui/draganddrop/target/DragCardTarget.js.kt
- writeopia_ui/src/jvmMain/kotlin/io/writeopia/ui/draganddrop/target/DragCardTarget.jvm.kt
- writeopia_ui/src/jvmMain/kotlin/io/writeopia/ui/draganddrop/target/DragRowTarget.jvm.kt
- writeopia_ui/src/nativeMain/kotlin/io/writeopia/ui/draganddrop/target/DragCardTarget.native.kt
Adding for images: 
- Possibility to select images in by clicking in the drag icon and swiping horizontally 
- Adding drag and drop for images.
> Polishing image

- application/common_flows/wide_screen_common/src/commonMain/kotlin/io/writeopia/notes/desktop/components/App.kt
- application/core/common_ui/build.gradle.kts
- application/core/common_ui/src/commonMain/kotlin/io/writeopia/commonui/workplace/WorkspaceConfigurationDialog.kt
- application/core/persistence_room/src/commonMain/kotlin/io/writeopia/persistence/room/data/daos/FolderDaoDelegator.kt
- application/core/persistence_room/src/commonMain/kotlin/io/writeopia/persistence/room/data/daos/NotesConfigurationRoomDaoDelegator.kt
- application/core/persistence_room/src/commonMain/kotlin/io/writeopia/persistence/room/extensions/FolderModelExtensions.kt
- application/core/persistence_room/src/commonMain/kotlin/io/writeopia/persistence/room/extensions/NotesConfigurationExtensions.kt
- application/core/utils/src/commonMain/kotlin/io/writeopia/common/utils/persistence/configuration/NotesConfigurationCommonEntity.kt
- application/core/utils/src/commonMain/kotlin/io/writeopia/common/utils/persistence/configuration/WorkspaceConfigRepository.kt
- application/core/utils/src/commonMain/kotlin/io/writeopia/common/utils/persistence/daos/NotesConfigurationCommonDao.kt
- application/core/utils/src/commonMain/kotlin/io/writeopia/common/utils/persistence/folder/FolderCommonEntity.kt
- application/core/utils/src/commonMain/kotlin/io/writeopia/common/utils/persistence/folder/FolderEntityExtensions.kt
- application/features/account/build.gradle.kts
- application/features/account/src/commonMain/kotlin/io/writeopia/account/ui/AccountMenuScreen.kt
- application/features/account/src/commonMain/kotlin/io/writeopia/account/ui/SettingsDialog.kt
- application/features/global_shell/src/commonMain/kotlin/io/writeopia/global/shell/di/SideMenuKmpInjector.kt
- application/features/global_shell/src/commonMain/kotlin/io/writeopia/global/shell/viewmodel/GlobalShellKmpViewModel.kt
- application/features/global_shell/src/commonMain/kotlin/io/writeopia/global/shell/viewmodel/GlobalShellViewModel.kt
- application/features/note_menu/src/commonMain/kotlin/io/writeopia/notemenu/data/repository/ConfigurationRepository.kt
- application/features/note_menu/src/commonMain/kotlin/io/writeopia/notemenu/data/repository/ConfigurationRoomRepository.kt
- application/features/note_menu/src/commonMain/kotlin/io/writeopia/notemenu/ui/screen/DesktopNotesMenu.kt
- application/features/note_menu/src/commonMain/kotlin/io/writeopia/notemenu/ui/screen/actions/DesktopNoteActionsMenu.kt
Moving the path configuration of workplace to the settings page
> refactor: Moving config of workplace path

- application/core/common_ui/src/commonMain/kotlin/io/writeopia/commonui/workplace/WorkspaceConfigurationDialog.kt
- application/core/utils/src/commonMain/kotlin/io/writeopia/common/utils/file/DirectoryChooserSave.kt
- application/core/utils/src/commonMain/kotlin/io/writeopia/common/utils/file/FileChooserSave.kt
- application/core/utils/src/commonMain/kotlin/io/writeopia/common/utils/icons/WrIcons.kt
- application/core/utils/src/commonMain/kotlin/io/writeopia/common/utils/icons/all/Zap.kt
- application/core/utils/src/jsMain/kotlin/io/writeopia/common/utils/file/FileChooserSave.js.kt
- application/core/utils/src/jvmMain/kotlin/io/writeopia/common/utils/file/FileChooserSave.jvm.kt
- application/core/utils/src/nativeMain/kotlin/io/writeopia/common/utils/file/FileChooserSave.native.kt
- application/features/editor/build.gradle.kts
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/ui/desktop/DesktopNoteEditorScreen.kt
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/ui/desktop/edit/menu/SideEditorOptions.kt
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/viewmodel/NoteEditorKmpViewModel.kt
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/viewmodel/NoteEditorViewModel.kt
- application/features/note_menu/src/commonMain/kotlin/io/writeopia/notemenu/ui/screen/DesktopNotesMenu.kt
- plugins/writeopia_export/src/commonMain/kotlin/io/writeopia/sdk/export/DocumentToJson.kt
- plugins/writeopia_export/src/commonMain/kotlin/io/writeopia/sdk/export/DocumentToMarkdown.kt
- plugins/writeopia_export/src/commonMain/kotlin/io/writeopia/sdk/export/DocumentWriter.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/manager/WriteopiaStateManager.kt
> feat: Exporting single files

- application/features/note_menu/src/commonMain/kotlin/io/writeopia/notemenu/viewmodel/ChooseNoteKmpViewModel.kt
Importing single files in current directory, instead of the directory where they where it was created.
> refactor: importing files in current directory

- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/TextDrawer.kt
This PR fixes a problem of showing "null" title when the value of there isn't any title yet.
> fix: Fixing nullable text

- application/composeApp/src/jvmMain/kotlin/io/writeopia/desktop/MainDesktop.kt
- application/core/persistence_room/src/commonMain/kotlin/io/writeopia/persistence/room/WriteopiaAplicationDatabase.kt
- application/features/editor/src/androidMain/kotlin/io/writeopia/editor/features/editor/ui/screen/NoteEditorScreen.kt
- application/features/editor/src/androidMain/kotlin/io/writeopia/editor/input/InputScreen.kt
- plugins/writeopia_persistence_room/src/commonMain/kotlin/io/writeopia/sdk/persistence/dao/room/RoomDocumentRepository.kt
- plugins/writeopia_persistence_room/src/commonMain/kotlin/io/writeopia/sdk/persistence/entity/story/StoryStepEntity.kt
- plugins/writeopia_persistence_room/src/commonMain/kotlin/io/writeopia/sdk/persistence/parse/StoryUnitParse.kt
- plugins/writeopia_persistence_sqldelight/src/commonMain/kotlin/io/writeopia/sdk/persistence/sqldelight/dao/DocumentSqlDao.kt
- plugins/writeopia_persistence_sqldelight/src/commonMain/sqldelight/io/writeopia/sdk/sql/StoryStepEntity.sq
- writeopia/src/commonMain/kotlin/io/writeopia/sdk/manager/SpansHandler.kt
- writeopia/src/commonMain/kotlin/io/writeopia/sdk/manager/WriteopiaManager.kt
- writeopia_models/src/commonMain/kotlin/io/writeopia/sdk/models/span/TextSpan.kt
- writeopia_ui/src/commonTest/kotlin/io/writeopia/ui/manager/WriteopiaStateManagerTest.kt
Adding:
- Persistence
- Splitting spans when adding a span inside a substring that already has the same span
> Polishing span support

- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/AiAnswerDrawer.kt
Adding drag to select the ai answer. Currently dragging to select it is not working.
> Adding drag to select to ai answer

- application/core/ollama/src/commonMain/kotlin/io/writeopia/OllamaRepository.kt
- application/core/ollama/src/commonMain/kotlin/io/writeopia/api/OllamaApi.kt
- application/core/ollama/src/commonMain/kotlin/io/writeopia/responses/DownloadModelResponse.kt
- application/features/account/src/commonMain/kotlin/io/writeopia/account/ui/SettingsDialog.kt
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/viewmodel/NoteEditorKmpViewModel.kt
- application/features/global_shell/src/commonMain/kotlin/io/writeopia/global/shell/viewmodel/GlobalShellKmpViewModel.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/components/multiselection/DragSelectionBox.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/AiAnswerDrawer.kt
In this PR:
- Showing an error message when it is not possible to download a model. 
- Starting with a default URL for Ollama. 
- Making AI answers selectable.
> Ollama polish

- application/core/theme/src/commonMain/kotlin/io/writeopia/theme/Theme.kt
- application/features/account/src/commonMain/kotlin/io/writeopia/account/ui/SettingsDialog.kt
Error link to Ollama website when an error happens in the load of models
> Adding link for ollama in the error message

- application/composeApp/src/jvmMain/kotlin/io/writeopia/desktop/MainDesktop.kt
- application/features/note_menu/src/commonMain/kotlin/io/writeopia/notemenu/viewmodel/ChooseNoteKmpViewModel.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/AiAnswerDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/keyboard/KeyboardEvent.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/manager/WriteopiaStateManager.kt
CMD + A now select all elements in documents
> Select with keyboard command

- application/core/persistence_room/src/commonMain/kotlin/io/writeopia/persistence/room/WriteopiaAplicationDatabase.kt
- backend/documents/documents_spring/src/main/java/io/writeopia/documents_spring/api/DocumentsRepository.kt
- backend/editor/api_editor/src/main/java/io/writeopia/api/editor/WriteopiaEditorApi.kt
- backend/editor/api_editor/src/main/java/io/writeopia/api/utils/DocumentsExtensions.kt
- gradle/libs.versions.toml
- kotlin-js-store/yarn.lock
Bumping versions for multiple libraries
> versions bump

- application/core/ollama/src/commonMain/kotlin/io/writeopia/persistence/OllamaSqlDao.kt
- application/features/account/src/commonMain/kotlin/io/writeopia/account/ui/AccountMenuScreen.kt
- application/features/account/src/commonMain/kotlin/io/writeopia/account/ui/SettingsDialog.kt
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/ui/desktop/edit/menu/SideEditorOptions.kt
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/viewmodel/NoteEditorKmpViewModel.kt
- writeopia/src/commonMain/kotlin/io/writeopia/sdk/model/story/Selection.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/WriteopiaEditor.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/manager/WriteopiaStateManager.kt
Now it is possible to make questions without selecting the text, just by placing the cursor in the desired line. 
It is also possible to select a sub text inside a line and make a question
> Making question without selection

- application/core/utils/src/commonMain/kotlin/io/writeopia/common/utils/icons/WrIcons.kt
- application/features/note_menu/src/commonMain/kotlin/io/writeopia/notemenu/ui/screen/configuration/molecules/NotesSelectionMenu.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/AiAnswerDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/icons/WrSdkIcons.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/icons/all/Files.kt
> Copy AI Answer

- application/composeApp/src/jvmMain/kotlin/io/writeopia/desktop/MainDesktop.kt
- application/core/utils/src/commonMain/kotlin/io/writeopia/common/utils/keyboard/KeyboardCommands.kt
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/ui/desktop/AppTextEditor.kt
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/ui/desktop/DesktopNoteEditorScreen.kt
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/viewmodel/NoteEditorKmpViewModel.kt
- application/features/note_menu/src/commonMain/kotlin/io/writeopia/notemenu/viewmodel/ChooseNoteKmpViewModel.kt
- writeopia_documents/Using_Commands_DDE16YFyYN.json
- writeopia_documents/Welcome!_816lZJxpi9.json
- writeopia_documents/writeopia_config_file.json
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/HeaderDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/keyboard/KeyboardEvent.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/manager/WriteopiaStateManager.kt
- Fixing header bug where typing space triggered a header edition
- Not selecting title with select all
- Cancel selection with ESC
> UI small fixes

- application/features/note_menu/src/commonMain/kotlin/io/writeopia/notemenu/ui/screen/documents/NoteItems.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/HeaderDrawer.kt
Now the tab to start button is part of the lazy list items and is also scrollable
> Making start button scrollable

- application/composeApp/src/jvmMain/kotlin/io/writeopia/desktop/MainDesktop.kt
Putting sqlite database inside .writeopia folder at root.
> Fixing database path

- plugins/writeopia_export/src/commonMain/kotlin/io/writeopia/sdk/export/DocumentToMarkdown.kt
- plugins/writeopia_export/src/commonTest/kotlin/io/writeopia/sdk/export/DocumentToMarkdownTest.kt
Adding support for unordered list items and checkboxes
> Markdown small improvement

- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/HeaderDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/model/DrawConfig.kt
When font family is set, the title places holder also uses the same font family
> Making title place holder set font family

- application/core/configuration/src/commonMain/kotlin/io/writeopia/core/configuration/repository/ConfigurationRoomRepository.kt
- application/core/configuration/src/commonMain/kotlin/io/writeopia/core/configuration/repository/ConfigurationSqlDelightRepository.kt
- application/core/configuration/src/commonMain/kotlin/io/writeopia/core/configuration/repository/InMemoryConfigurationRepository.kt
- application/core/configuration/src/jvmMain/kotlin/io/writeopia/core/configuration/di/AppConfigurationInjector.jvm.kt
- application/core/documents/src/jvmMain/kotlin/io/writeopia/core/folders/di/FoldersInjector.jvm.kt
- application/core/utils/src/androidMain/kotlin/io/writeopia/common/utils/file/FileUtils.android.kt
- application/core/utils/src/commonMain/kotlin/io/writeopia/common/utils/file/FileUtils.kt
- application/core/utils/src/jsMain/kotlin/io/writeopia/common/utils/file/FileUtils.js.kt
- application/core/utils/src/jvmMain/kotlin/io/writeopia/common/utils/file/FileUtils.jvm.kt
- application/core/utils/src/nativeMain/kotlin/io/writeopia/common/utils/file/FileUtils.native.kt
- application/features/note_menu/src/commonMain/kotlin/io/writeopia/notemenu/data/usecase/NotesUseCase.kt
- application/features/note_menu/src/commonMain/kotlin/io/writeopia/notemenu/ui/screen/configuration/atoms/SortOptions.kt
- application/features/note_menu/src/commonMain/kotlin/io/writeopia/notemenu/ui/screen/configuration/molecules/NotesConfigurationMenu.kt
- application/features/note_menu/src/commonMain/kotlin/io/writeopia/notemenu/viewmodel/ChooseNoteKmpViewModel.kt
- application/features/search/src/commonMain/kotlin/io/writeopia/features/search/di/KmpSearchInjection.kt
- Fixing refresh of order options
- Fixing folder check when saving workspace
> Fixing sort options update

- application/core/resources/config/ktlint/baseline.xml
- application/core/resources/src/commonMain/composeResources/values/strings.xml
- application/core/resources/src/commonMain/kotlin/io/writeopia/resources/WrStrings.kt
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/ui/desktop/edit/menu/SideEditorOptions.kt
- plugins/writeopia_export/src/commonMain/kotlin/io/writeopia/sdk/export/DocumentToMarkdown.kt
- plugins/writeopia_export/src/commonMain/kotlin/io/writeopia/sdk/export/files/KmpFileWritter.kt
Adding button to export document as markdown.
> Fixing markdown export

- application/composeApp/src/jvmMain/kotlin/io/writeopia/desktop/MainDesktop.kt
- application/core/utils/src/androidMain/kotlin/io/writeopia/common/utils/keyboard/KeyboardExtensions.android.kt
- application/core/utils/src/commonMain/kotlin/io/writeopia/common/utils/keyboard/KeyboardExtensions.kt
- application/core/utils/src/jsMain/kotlin/io/writeopia/common/utils/keyboard/KeyboardExtensions.js.kt
- application/core/utils/src/jvmMain/kotlin/io/writeopia/common/utils/keyboard/KeyboardExtensions.jvm.kt
- application/core/utils/src/nativeMain/kotlin/io/writeopia/common/utils/keyboard/KeyboardExtensions.native.kt
- writeopia_ui/build.gradle.kts
- writeopia_ui/src/commonMain/composeResources/values-en/strings.xml
- writeopia_ui/src/commonMain/composeResources/values-pt/strings.xml
- writeopia_ui/src/commonMain/composeResources/values/strings.xml
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/AiAnswerDrawer.kt
At the moment, the app is using Option as the multi-selection shortcut, but this creates a problem with adding special characters in the text editor. 
This PR changes the shortcut for multi-selection.
> Changing multi selection shortcut

- application/common_flows/wide_screen_common/src/commonMain/kotlin/io/writeopia/notes/desktop/components/App.kt
- application/common_flows/wide_screen_common/src/jvmTest/kotlin/io/writeopia/menu/Utils.kt
- application/composeApp/src/commonMain/kotlin/io/writeopia/mobile/AppMobile.kt
- application/composeApp/src/jvmMain/kotlin/io/writeopia/desktop/MainDesktop.kt
- application/core/navigation/src/commonMain/kotlin/io/writeopia/navigation/Navigation.kt
- application/core/utils/src/commonMain/kotlin/io/writeopia/common/utils/keyboard/KeyboardCommands.kt
- application/features/editor/src/androidMain/kotlin/io/writeopia/editor/features/editor/ui/screen/TextEditorScreen.android.kt
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/ui/desktop/DesktopNoteEditorScreen.kt
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/ui/screen/TextEditorScreen.kt
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/viewmodel/NoteEditorKmpViewModel.kt
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/navigation/EditorNavigation.kt
- application/features/editor/src/jsMain/kotlin/io/writeopia/editor/features/editor/ui/screen/TextEditorScreen.js.kt
- application/features/editor/src/jvmMain/kotlin/io/writeopia/editor/features/editor/ui/screen/TextEditorScreen.jvm.kt
- application/features/editor/src/nativeMain/kotlin/io/writeopia/editor/features/editor/ui/screen/TextEditorScreen.native.kt
- application/web/src/jsMain/kotlin/io/writeopia/web/MainWeb.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/backstack/PerStateBackstackManager.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/keyboard/KeyboardEvent.kt
This PR adds a redo shortcut. It is still necessary to fix the undo/redo logic so it always works.
> Adding redo short cut

- application/features/note_menu/src/commonMain/kotlin/io/writeopia/notemenu/ui/screen/documents/NoteItems.kt
- writeopia/src/commonMain/kotlin/io/writeopia/sdk/preview/PreviewParser.kt
- writeopia_ui/build.gradle.kts
- writeopia_ui/config/ktlint/baseline.xml
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/ImageDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/factory/KeyEventListenerFactory.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/preview/ImagePreviewDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/preview/TextPreviewDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/preview/UnOrderedListItemPreviewDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/image/ImageLoadConfig.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/manager/WriteopiaStateManager.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/modifiers/StepsModifier.kt
- writeopia_ui/src/jsMain/kotlin/io/writeopia/ui/draganddrop/target/DragRowTarget.js.kt
- writeopia_ui/src/jvmMain/kotlin/io/writeopia/ui/draganddrop/target/DragCardTarget.jvm.kt
- writeopia_ui/src/nativeMain/kotlin/io/writeopia/ui/draganddrop/target/external/HandleImageDrop.native.kt
This PR create a preview for images:
> Preview for images

- application/features/note_menu/src/androidMain/kotlin/io/writeopia/notemenu/ui/screen/file/FileChooserLoad.android.kt
- application/features/note_menu/src/commonMain/kotlin/io/writeopia/notemenu/ui/screen/file/FileChooserLoad.kt
- application/features/note_menu/src/commonMain/kotlin/io/writeopia/notemenu/viewmodel/ChooseNoteKmpViewModel.kt
- application/features/note_menu/src/commonMain/kotlin/io/writeopia/notemenu/viewmodel/ChooseNoteViewModel.kt
- application/features/note_menu/src/jsMain/kotlin/io/writeopia/notemenu/ui/screen/file/FileChooserLoad.js.kt
- application/features/note_menu/src/jvmMain/kotlin/io/writeopia/notemenu/ui/screen/file/FileChooserLoad.jvm.kt
- application/features/note_menu/src/jvmMain/kotlin/io/writeopia/notemenu/ui/screen/menu/NotesMenuScreen.jvm.kt
- application/features/note_menu/src/nativeMain/kotlin/io/writeopia/notemenu/ui/screen/file/FileChooserLoad.native.kt
- writeopia_models/src/commonMain/kotlin/io/writeopia/sdk/models/files/ExternalFile.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/manager/WriteopiaStateManager.kt
- writeopia_ui/src/jvmMain/kotlin/io/writeopia/ui/draganddrop/target/external/HandleImageDrop.jvm.kt
Drop an image to create a note
closes #390
https://github.com/user-attachments/assets/8a7ceaff-565f-45ce-af5d-910eb70a86de
**Suggested by Haroldo. Thank you!!**
> Dropping an image create a note

- application/core/utils/src/androidMain/kotlin/io/writeopia/common/utils/file/SaveImage.android.kt
- application/core/utils/src/commonMain/kotlin/io/writeopia/common/utils/file/SaveImage.kt
- application/core/utils/src/jsMain/kotlin/io/writeopia/common/utils/file/SaveImage.js.kt
- application/core/utils/src/jvmMain/kotlin/io/writeopia/common/utils/file/SaveImage.jvm.kt
- application/core/utils/src/nativeMain/kotlin/io/writeopia/common/utils/file/SaveImage.native.kt
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/viewmodel/NoteEditorKmpViewModel.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/manager/WriteopiaStateManager.kt
Moving images to workspace instead of using then from the original path
> Move images to workspace

- application/core/utils/src/jvmMain/kotlin/io/writeopia/common/utils/file/SaveImage.jvm.kt
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/viewmodel/NoteEditorKmpViewModel.kt
- application/features/note_menu/src/commonMain/kotlin/io/writeopia/notemenu/di/NotesMenuKmpInjection.kt
- application/features/note_menu/src/commonMain/kotlin/io/writeopia/notemenu/viewmodel/ChooseNoteKmpViewModel.kt
- application/features/note_menu/src/jvmTest/kotlin/io/writeopia/notemenu/viewmodel/ChooseNoteViewModelTest.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/AiAnswerDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/DesktopTextItemDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/DividerDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/DocumentLinkDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/factory/CommonDrawers.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/manager/WriteopiaStateManager.kt
Improving add of external image by drag and drop
> Improving external image add

- application/core/persistence_sqldelight/src/commonMain/kotlin/io/writeopia/sqldelight/extensions/FoldersExtensions.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/HeaderDrawer.kt
Showing different icon change the users selects to change it
> Changing folder icon

- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/edition/TextCommandHandler.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/manager/WriteopiaStateManager.kt
It shouldn't be possible to change title type.
> Excluding title from commands

- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/manager/BackpressureBuffer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/manager/WriteopiaStateManager.kt
- writeopia_ui/src/commonTest/kotlin/io/writeopia/ui/manager/WriteopiaStateManagerTest.kt
https://github.com/user-attachments/assets/418b4ff8-34ff-4c73-ad74-d050407e9eaa
> Fixing selection of multiple lines

- application/features/note_menu/src/androidMain/kotlin/io/writeopia/notemenu/ui/screen/menu/NotesMenuScreen.android.kt
- application/features/note_menu/src/commonMain/kotlin/io/writeopia/notemenu/navigation/NotesMenuNavigation.kt
- application/features/note_menu/src/commonMain/kotlin/io/writeopia/notemenu/ui/screen/DesktopNotesMenu.kt
- application/features/note_menu/src/commonMain/kotlin/io/writeopia/notemenu/ui/screen/documents/NoteItems.kt
- application/features/note_menu/src/commonMain/kotlin/io/writeopia/notemenu/ui/screen/menu/NotesMenuScreen.kt
- application/features/note_menu/src/jsMain/kotlin/io/writeopia/notemenu/ui/screen/menu/NotesMenuScreen.js.kt
- application/features/note_menu/src/jvmMain/kotlin/io/writeopia/notemenu/ui/screen/menu/NotesMenuScreen.jvm.kt
- application/features/note_menu/src/nativeMain/kotlin/io/writeopia/notemenu/ui/screen/menu/NotesMenuScreen.native.kt
https://github.com/user-attachments/assets/7cd38ca5-26da-45c1-ada0-76612990eaf9
Unfortunately, this creates some occasional crashes, so I need to wait until this animation is fixed by Jetbrains before merging this.
> Transition for folders

- application/composeApp/build.gradle.kts
- application/core/resources/src/commonMain/composeResources/values-en/strings.xml
- application/core/resources/src/commonMain/composeResources/values-pt/strings.xml
- application/core/resources/src/commonMain/composeResources/values/strings.xml
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/ui/TextEditor.kt
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/viewmodel/NoteEditorKmpViewModel.kt
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/viewmodel/NoteEditorViewModel.kt
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/viewmodel/PromptService.kt
- writeopia_ui/config/ktlint/baseline.xml
- writeopia_ui/src/androidMain/kotlin/io/writeopia/ui/drawer/factory/DefaultDrawersAndroid.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/factory/DrawersFactory.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/icons/WrSdkIcons.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/icons/all/WandSparkles.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/manager/WriteopiaStateManager.kt
- writeopia_ui/src/jsMain/kotlin/io/writeopia/ui/drawer/factory/DefaultDrawersJs.kt
- writeopia_ui/src/jvmMain/kotlin/io/writeopia/ui/drawer/factory/DefaultDrawersDesktop.kt
Now you can generate a whole section of the document using AI
https://github.com/user-attachments/assets/93f1c152-a746-4c60-949d-efd22cd89ae1
> Section generation

- application/core/forcegraph/src/commonMain/kotlin/io/writeopia/forcegraph/ForceDirectedGraph.kt
- application/features/documents_graph/src/commonMain/kotlin/io/writeopia/documents/graph/ItemData.kt
- application/features/documents_graph/src/commonMain/kotlin/io/writeopia/documents/graph/extensions/GraphExtensions.kt
- application/features/documents_graph/src/commonMain/kotlin/io/writeopia/documents/graph/navigation/NavigateDocumentGraph.kt
- application/features/documents_graph/src/commonMain/kotlin/io/writeopia/documents/graph/ui/DocumentsGraphViewModel.kt
> Improving force graph

- application/core/forcegraph/src/commonMain/kotlin/io/writeopia/forcegraph/ForceDirectedGraph.kt
- application/core/forcegraph/src/commonMain/kotlin/io/writeopia/forcegraph/Graph.kt
- application/core/forcegraph/src/commonMain/kotlin/io/writeopia/forcegraph/model/Graph.kt
- application/features/documents_graph/src/commonMain/kotlin/io/writeopia/documents/graph/extensions/GraphExtensions.kt
- application/features/documents_graph/src/commonMain/kotlin/io/writeopia/documents/graph/navigation/NavigateDocumentGraph.kt
- application/features/documents_graph/src/commonMain/kotlin/io/writeopia/documents/graph/ui/DocumentsGraphViewModel.kt
Fixing the limit of the nodes in the chart
> Fixing limit for nodes

- application/composeApp/src/jvmMain/kotlin/io/writeopia/desktop/MainDesktop.kt
- application/core/persistence_sqldelight/src/commonMain/sqldelight/migration/3.sqm
- application/core/persistence_sqldelight/src/commonMain/sqldelight/migration/4.sqm
- application/core/persistence_sqldelight/src/commonMain/sqldelight/migration/5.sqm
- application/core/resources/src/commonMain/composeResources/values-en/strings.xml
- application/core/resources/src/commonMain/composeResources/values-pt/strings.xml
- application/core/resources/src/commonMain/composeResources/values/strings.xml
- Changing base url
- Fixing migration of DB
> Adding cloud

- application/core/ollama/src/commonMain/kotlin/io/writeopia/persistence/OllamaDao.kt
- application/core/ollama/src/commonMain/kotlin/io/writeopia/persistence/OllamaSqlDao.kt
> Fixing url of ollama

- application/core/ollama/src/commonMain/kotlin/io/writeopia/OllamaRepository.kt
- application/core/ollama/src/commonMain/kotlin/io/writeopia/di/OllamaInjection.kt
- application/core/resources/config/ktlint/baseline.xml
- application/core/resources/src/commonMain/composeResources/values-en/strings.xml
- application/core/resources/src/commonMain/composeResources/values-pt/strings.xml
- application/core/resources/src/commonMain/composeResources/values/strings.xml
- application/core/resources/src/commonMain/kotlin/io/writeopia/resources/WrStrings.kt
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/ui/desktop/DesktopNoteEditorScreen.kt
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/ui/desktop/edit/menu/SideEditorOptions.kt
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/viewmodel/NoteEditorKmpViewModel.kt
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/viewmodel/NoteEditorViewModel.kt
- application/features/global_shell/src/commonMain/kotlin/io/writeopia/global/shell/viewmodel/GlobalShellKmpViewModel.kt
Changing model from inside the document
https://github.com/user-attachments/assets/e253eb5e-0d77-489a-b63f-f5d60c59179a
> Changing model from inside the document

- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/viewmodel/NoteEditorKmpViewModel.kt
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/viewmodel/NoteEditorViewModel.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/components/EditionScreen.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/TextToolbox.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/content/TextDrawer.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/drawer/factory/CommonDrawers.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/manager/WriteopiaStateManager.kt
- writeopia_ui/src/jvmMain/kotlin/io/writeopia/ui/drawer/factory/DefaultDrawersDesktop.kt
Adding a toolbox of option when text is selected
> Adding text toolbox

- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/ui/desktop/DesktopNoteEditorScreen.kt
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/ui/desktop/edit/menu/SideEditorOptions.kt
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/viewmodel/NoteEditorKmpViewModel.kt
- application/features/editor/src/commonMain/kotlin/io/writeopia/editor/features/editor/viewmodel/NoteEditorViewModel.kt
- writeopia_ui/src/commonMain/kotlin/io/writeopia/ui/manager/WriteopiaStateManager.kt
Adding buttons to create titles in the text
> Adding title buttons
